### ISSUE TITLE
co-citation análisis con keywords

### ISSUE THREAD

**Issue by sofiafoladori** [guillermo-orjuela/bibliometriar#1]
Hola, 
Después de hacer co-citation análisis con keywords llego a 3 clústeres con la función networkPlot. 
Necesito saber cuáles son los artículos de mi base de dados vinculado a cada clúster. ¿Alguna idea de cómo hacer un dataframe con el nombre del articulo y su respectivo número de clúster? 
Muchas Gracias!

**Comment by guillermo-orjuela** [comment]
Hola.
Por favor verifica si hiciste análisis de co-citación o de co-ocurrencias. Según la documentación del paquete de Bibliometrix la co-citación solo se puede hacer con la información de los autores, referencias y revistas.
En todo caso, para extraer la información de una red, puedes hacer lo siguiente:
Supongamos que la información de la función networkPlot está en un objeto llamado np.
df <- np$cluster_res 
Esto crea una base de datos con la información de la red np.

**Comment by sofiafoladori** [comment]
Hola Guillermo, 
Muchas gracias por la rápida respuesta. 
Me equivoqué al escribir, hice análisis de co-ocurrencias de las keywords
Trate de hacer df <- net$cluster_res pero en NET no hay ninguna información del artículo, solo consigo extraer las keywords y sus respectivos clústeres. No estoy consiguiendo encontrar alguna información que me permita vincular el artículo. 

Script:
##Keyword co-occurrences
# Create keyword co-occurrences network
NetMatrix <- biblioNetwork(m_bib, analysis = "co-occurrences", network = "keywords", sep = ";")
# Plot the network
net <- networkPlot(NetMatrix3, normalize="association", weighted=T, n = 30,  Title = "Keyword Co-occurrences", type = "fruchterman", size=T, edgesize = 5,labelsize=0.7)
df <- net$cluster_res
#me devuelve las keywords (adentro de vertex) y el cluster en cual están.

**Comment by guillermo-orjuela** [comment]
Creo que una forma de hacerlo es extraer de la base de datos m_bib los artículos asociados a las keywords que están en la base de datos df creada en el paso anterior, la cual contiene las keywords por cluster.

Ahora bien, al hacer esto pueden aparecer artículos en más de un cluster en caso que un artículo tenga keywords asociadas a más de un cluster.

No conozco un método usando las funciones del paquete Bibliometrix, pero tal vez podrías hacerlo usando el paquete stringr. Se crea el objeto df_1 a partir de la base de datos m_bib de la cual se extraen todos los artículos que tengan en la columna DE (la que contiene las keywords) la palabra PERFORMANCE.

df_1 <- m_bib %>% filter(str_detect(DE, "PERFORMANCE"))

Si deseas incluir más palabras puedes hacerlo usando el símbolo |

df_1 <- m_bib %>% filter(str_detect(DE, "PERFORMANCE|DRIVERS"))

De esta manera podrías crear un vector de palabras con las keywords asociadas a un cluster y filtrar en la base de datos m_bib los artículos que tengan al menos 1 keyword en la columna DE. Ten en cuenta este criterio de filtración.

Aquí puedes ver un ejemplo: https://blog.exploratory.io/filter-with-text-data-952df792c2ba

**Comment by sofiafoladori** [comment]
¡Muchísimas gracias! ¡Con eso conseguí extraer la información que quería!
